# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "disable-active-workflows"
version = "1.0.0"
description = "Disable active workflows in a repository"
readme = "README.md"